services:
  - type: web
    name: flask-api
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn api:app --bind 0.0.0.0:10000"
    envVars:
      - key: PORT
        value: 10000
